### ISSUE TITLE
Basic Game Play in GrSim

### ISSUE THREAD

**Issue by elinrydebrink** [LiU-SeeGoals/controller#14]
Simulating basic game play in grsim is a major milestone.

To accomplish this there several things need to be implemented. This epic aims to track these thing all in one place:

- [x] Add geometry data to game state
- [x] Implement basic robot actions in grim
- [ ] Implement basic AI?
